"""
jrivermcws.mcc
~~~~~~~~~~~~~~

Contains two dictionaries mcc_cmds and mcc_codes that provide lookup of MC commands

These commands can be sent by command-line in Windows, but the Unix version of JRiver
doesn't support it so they must be sent via MCWS.


* Pulled from https://wiki.jriver.com/index.php/Media_Center_Core_Commands#MC_Commands
with regexp (\d+)\s*(\S+)\s+(.+) -> $1: ('$2', '$3'),

~~~~~~~~~~~~~~~

Copyright Michael Adkins 2017
Distributed under the MIT License.
See accompanying file LICENSE.md file or copy at http://opensource.org/licenses/MIT

"""

_cmds = {

    #Playback
    10000: ('MCC_PLAY_PAUSE', 'ignore'),
    10001: ('MCC_PLAY', 'ignore'),
    10002: ('MCC_STOP', 'bool bDisplayError'),
    10003: ('MCC_NEXT', 'int nFlags (1: bNotActualNext, 2: bNoChapters)'),
    10004: ('MCC_PREVIOUS', 'int nFlags (1: reserved, 2: bNoChapters, 4: no seek to beginning)'),
    10005: ('MCC_SHUFFLE', '0: toggle shuffle mode; 1: shuffle, jump to PN; 2: shuffle, no jump; 3: off; 4: on; 5:automatic'),
    10006: ('MCC_CONTINUOUS', '0: toggle continuous; 1: off; 2: playlist; 3: song; 4: stop after each'),
    10007: ('MCC_OBSOLETE_10007', 'ignore'),
    10008: ('MCC_FAST_FORWARD', 'int nRate'),
    10009: ('MCC_REWIND', 'int nRate'),
    10010: ('MCC_STOP_CONDITIONAL', 'ignore'),
    10011: ('MCC_SET_ZONE', 'int nZoneIndex (-1 toggles forward, -2 toggles backwards)'),
    10012: ('MCC_TOGGLE_DISPLAY', 'bool bExcludeTheaterView'),
    10013: ('MCC_SHOW_WINDOW', 'bool bJumpToPlayingNow'),
    10014: ('MCC_MINIMIZE_WINDOW', 'ignore'),
    10015: ('MCC_PLAY_CPLDB_INDEX', 'int nIndex'),
    10016: ('MCC_SHOW_DSP_STUDIO', 'ignore'),
    10017: ('MCC_VOLUME_MUTE', '0: toggle; 1: mute; 2: unmute'),
    10018: ('MCC_VOLUME_UP', 'int nDeltaPercent'),
    10019: ('MCC_VOLUME_DOWN', 'int nDeltaPercent'),
    10020: ('MCC_VOLUME_SET', 'int nPercent'),
    10021: ('MCC_SHOW_PLAYBACK_OPTIONS', 'ignore'),
    10022: ('MCC_SET_PAUSE', 'bool bPause (-1 toggles)'),
    10023: ('MCC_SET_CURRENTLY_PLAYING_RATING', 'int nRating (1 through 5; 0 clears, but see here.)'),
    10024: ('MCC_SHOW_PLAYBACK_ENGINE_MENU', 'screen point (loword: x, hiword: y) -- must send directly'),
    10025: ('MCC_PLAY_NEXT_PLAYLIST', 'ignore'),
    10026: ('MCC_PLAY_PREVIOUS_PLAYLIST', 'ignore'),
    10027: ('MCC_MAXIMIZE_WINDOW', 'ignore'),
    10028: ('MCC_RESTORE_WINDOW', 'ignore'),
    10029: ('MCC_SET_PLAYERSTATUS', 'PLAYER_STATUS_CODES Code'),
    10030: ('MCC_SET_ALTERNATE_PLAYBACK_SETTINGS', 'bool bAlternateSettings (-1 toggles)'),
    10031: ('MCC_SET_PREVIEW_MODE_SETTINGS', 'low 12 bits: int nDurationSeconds, high 12 bits: int nStartSeconds'),
    10032: ('MCC_SHOW_PLAYBACK_ENGINE_DISPLAY_PLUGIN_MENU', 'screen point (loword: x, hiword: y) -- must send directly'),
    10033: ('MCC_DVD_MENU', 'ignore'),
    10034: ('MCC_SEEK_FORWARD', 'int nMilliseconds (0 means default -- varies depending on playback type)'),
    10035: ('MCC_SEEK_BACK', 'int nMilliseconds (0 means default -- varies depending on playback type)'),
    10036: ('MCC_STOP_AFTER_CURRENT_FILE', 'bool bStopAfterCurrentFile (-1 toggles)'),
    10037: ('MCC_DETACH_DISPLAY', 'bool bDetach (-1 toggles)'),
    10038: ('MCC_SET_MODE_ZONE_SPECIFIC', 'UI_MODES mode'),
    10039: ('MCC_STOP_INTERNAL', 'ignore'),
    10040: ('MCC_PLAYING_NOW_REMOVE_DUPLICATES', 'ignore'),
    10041: ('MCC_SHUFFLE_REMAINING', 'ignore'),
    10042: ('MCC_PLAY_FIRST_FILE', 'ignore'),
    10043: ('MCC_PLAY_LAST_FILE', 'ignore'),
    10044: ('MCC_PLAY_FILE_BY_STRING', 'BSTR bstrFile (deleted by receiver)'),
    10045: ('MCC_PLAY_FILE_AGAIN', 'ignore'),
    10046: ('MCC_HANDLE_PLAYBACK_ERROR', 'ignore'),
    10047: ('MCC_PLAY_AUTOMATIC_PLAYLIST', 'BSTR bstrSeed (deleted by receiver)'),
    10048: ('MCC_SEEK', 'int nPositionMilliseconds'),
    10049: ('MCC_CLEAR_PLAYING_NOW_ZONE_SPECIFIC', '0: all files; 1: leave playing file'),
    10050: ('MCC_PLAY_RADIO_LAST_FM', 'ignore'),
    10051: ('MCC_SHOW_ON_SCREEN_DISPLAY', '0: position bar'),
    10052: ('MCC_SET_SUBTITLES', 'int nIndex (-1 toggles forward, -2 toggles backwards)'),
    10053: ('MCC_SET_AUDIO_STREAM', 'int nIndex (-1 toggles forward, -2 toggles backwards)'),
    10054: ('MCC_SET_VIDEO_STREAM', 'int nIndex (-1 toggles forward, -2 toggles backwards)'),
    10055: ('MCC_VIDEO_SCREEN_GRAB', '0: use as thumbnail; 1: save as external file'),
    10056: ('MCC_SET_VOLUME_MODE', 'int nMode (internal type EPlaybackVolumeModes) (0: application, 1: internal; 2: system; 3: disabled)'),
    10057: ('MCC_RESTART_PLAYBACK', 'ignore'),
    10058: ('MCC_ZONE_SWITCH', 'ignore'),
    10059: ('MCC_SKIP_TO', 'SKIP_TO_MODES Mode'),
    10060: ('MCC_LINK_ZONE', 'int nZoneID'),
    10061: ('MCC_UNLINK_ZONE', 'ignore'),
    10062: ('MCC_PLAY_RADIO_MEDIANET', 'ignore'),
    10063: ('MCC_CLEAR_PLAYED_ZONE_SPECIFIC', 'ignore'),
    10064: ('MCC_PLAY_LAST_TV_CHANNEL', 'ignore'),

    # File
    20000: ('MCC_OPEN_FILE', 'ignore'),
    20001: ('MCC_OPEN_URL', 'ignore'),
    20002: ('MCC_PRINT_LIST', 'ignore'),
    20003: ('MCC_EXPORT_PLAYLIST', 'int nPlaylistID (-1 for active view)'),
    20004: ('MCC_EXPORT_ALL_PLAYLISTS', 'bool bSilent'),
    20005: ('MCC_UPLOAD_FILES', 'ignore'),
    20006: ('MCC_EMAIL_FILES', 'ignore'),
    20007: ('MCC_EXIT', 'int nMode (0: normal, 1: force close (close media server), 2: force close (allow media server))'),
    20008: ('MCC_UPDATE_LIBRARY', 'ignore'),
    20009: ('MCC_CLEAR_LIBRARY', 'ignore'),
    20010: ('MCC_EXPORT_LIBRARY', 'ignore'),
    20011: ('MCC_BACKUP_LIBRARY', 'int nMode (0: normal, 1: silent automatic backup)'),
    20012: ('MCC_RESTORE_LIBRARY', 'ignore'),
    20013: ('MCC_LIBRARY_MANAGER', 'ignore'),
    20014: ('MCC_IMAGE_ACQUIRE', 'ignore'),
    20015: ('MCC_PRINT_IMAGES', 'MFKEY nKey (-1 for selected files)'),
    20016: ('MCC_PRINT', 'ignore'),
    20017: ('MCC_OBSOLETE_20017', 'ignore'),
    20018: ('MCC_OBSOLETE_20018', 'ignore'),
    20019: ('MCC_OBSOLETE_20019', 'ignore'),
    20020: ('MCC_OBSOLETE_20020', 'ignore'),
    20021: ('MCC_OBSOLETE_20021', 'ignore'),
    20022: ('MCC_OBSOLETE_20022', 'ignore'),
    20023: ('MCC_OBSOLETE_20023', 'ignore'),
    20024: ('MCC_IMPORT_PLAYLIST', 'ignore'),
    20025: ('MCC_LOAD_LIBRARY', 'int nLibraryIndex'),
    20026: ('MCC_SYNC_LIBRARY', 'ignore'),
    20027: ('MCC_EMAIL_PODCAST_FEED', 'ignore'),
    20028: ('MCC_LOAD_LIBRARY_READ_ONLY', 'int nLibraryIndex'),
    20029: ('MCC_ADD_LIBRARY', 'ignore'),
    20030: ('MCC_EXPORT_ITUNES', 'ignore'),
    20031: ('MCC_DISCONNECT_LIBRARY', 'ignore'),
    20032: ('MCC_SYNC_WITH_LIBRARY_SERVER', 'ignore'),
    20033: ('MCC_STOP_ALL_ZONES', 'bool bStopRemoteZones'),
    20034: ('MCC_CLONE_LIBRARY', 'int nLibraryIndex'),
    20035: ('MCC_OPEN_LIVE', 'ignore'),

    # Edit
    21000: ('MCC_COPY', 'ignore'),
    21001: ('MCC_PASTE', 'ignore'),
    21002: ('MCC_SELECT_ALL', 'ignore'),
    21003: ('MCC_SELECT_INVERT', 'ignore'),
    21004: ('MCC_DELETE', 'bool bAggressive'),
    21005: ('MCC_RENAME', 'ignore'),
    21006: ('MCC_UNDO', 'ignore'),
    21007: ('MCC_REDO', 'ignore'),
    21008: ('MCC_QUICK_SEARCH', 'bool bRepeatLastSearch'),
    21009: ('MCC_ADD_PLAYLIST', 'MEDIAFILE_INFO_ARRAY * paryFiles = NULL'),
    21010: ('MCC_ADD_SMARTLIST', 'ignore'),
    21011: ('MCC_ADD_PLAYLIST_GROUP', 'ignore'),
    21012: ('MCC_PROPERTIES', 'MEDIAFILE_INFO_ARRAY * paryFiles = NULL (-1 toggles) (note: never PostMessage(...) a pointer)'),
    21013: ('MCC_TOGGLE_TAGGING_MODE', 'ignore'),
    21014: ('MCC_CUT', 'ignore'),
    21015: ('MCC_DESELECT_ALL', 'ignore'),
    21016: ('MCC_DELETE_ALL', 'bool bAggressive'),
    21017: ('MCC_ADD_PODCAST_FEED', 'ignore'),
    21018: ('MCC_EDIT_PODCAST_FEED', 'ignore'),
    21019: ('MCC_ADD_PODCAST_DEFAULTS', 'ignore'),
    21020: ('MCC_CREATE_STOCK_SMARTLISTS', 'ignore'),
    21021: ('MCC_ENABLE_PODCAST_DOWNLOAD', 'ignore'),
    21022: ('MCC_DISABLE_PODCAST_DOWNLOAD', 'ignore'),
    21023: ('MCC_EDIT_PLAYLIST', 'ignore'),
    21024: ('MCC_EDIT_PLAYING_NOW', 'int nZoneID'),
    21025: ('MCC_EDIT_DISC_INFORMATION', 'ignore'),
    21026: ('MCC_EDIT_SMARTLIST', 'int nPlaylistID'),
    21027: ('MCC_REFRESH_PODCAST_FEED', 'ignore'),
    21028: ('MCC_LOOKUP_MOVIE_INFORMATION', 'ignore'),
    21029: ('MCC_ADD_ZONE', 'ignore'),
    21030: ('MCC_ADD_AUTOMATIC_PLAYLIST', 'ignore'),
    21031: ('MCC_SET_WRITE_TAGS', 'bool bWriteTags (-1 toggles)'),
    21032: ('MCC_PASTE_TAGS', 'ignore'),
    21033: ('MCC_SHUFFLE_SELECTION', 'ignore'),

    # View
    22000: ('MCC_TOGGLE_MODE', 'UI_MODES mode'),
    22001: ('MCC_THEATER_VIEW', '0: Toggle, 1: Home, 2: Playing Now, 3: Audio, 4: Images, 5: Video, 6: Playlists, 7: CD & DVD, 8: TV, 9: TV Guide, 10: TV Recordings'),
    22002: ('MCC_PARTY_MODE', 'ignore'),
    22003: ('MCC_SHOW_TREE_ROOT', '-1: Toggle, 0: Hide, 1: Show'),
    22004: ('MCC_FIND_MEDIA', 'wchar * pstrSearch (note: memory will be deleted by receiver)'),
    22005: ('MCC_BACK', 'int nLevels (0 does 1 level)'),
    22006: ('MCC_FORWARD', 'int nLevels (0 does 1 level)'),
    22007: ('MCC_REFRESH', 'int nFlags (1: no webpage refresh)'),
    22008: ('MCC_SET_LIST_STYLE', 'int nListStyle (-1 toggles)'),
    22009: ('MCC_SET_MODE', 'UI_MODES mode'),
    22010: ('MCC_OBSOLETE_22010', 'ignore'),
    22011: ('MCC_OBSOLETE_22011', 'ignore'),
    22012: ('MCC_SHOW_RECENTLYIMPORTED', 'ignore'),
    22013: ('MCC_SHOW_TOPHITS', 'ignore'),
    22014: ('MCC_SHOW_RECENTLYPLAYED', 'ignore'),
    22015: ('MCC_SET_MEDIA_MODE', 'int nMediaMode'),
    22016: ('MCC_OBSOLETE_22016', 'ignore'),
    22017: ('MCC_SET_SERVER_MODE', 'bool bServerMode'),
    22018: ('MCC_SET_MODE_FOR_EXTERNAL_PROGRAM_LAUNCH', 'int nType (0: starting external app, 1: ending external app)'),
    22019: ('MCC_SET_MODE_FOR_SECOND_INSTANCE_LAUNCH', 'UI_MODES mode'),
    22020: ('MCC_HOME', 'ignore'),
    22021: ('MCC_ROLLUP_VIEW_HEADER', 'bool bRollup (-1: toggle)'),
    22022: ('MCC_FOCUS_SEARCH_CONTROL', 'ignore'),
    22023: ('MCC_SET_ACTIVE_VIEW_KEY', 'int nViewKey (-1: toggle, -2: toggle backwards, -3: new view)'),
    22024: ('MCC_CLOSE_VIEW_KEY', 'int nViewKey (-1: current view)'),
    22025: ('MCC_VIEW_ZOOM_SET', 'int nZoomPercentage'),
    22026: ('MCC_VIEW_ZOOM_INCREMENT', 'int nZoomDeltaPercentage'),
    22027: ('MCC_FIND_MEDIA_WITH_WIZARD', 'ignore'),
    22028: ('MCC_SET_USER', 'int nUserId'),
    22029: ('MCC_SHOW_TREE', 'bool bShowTree (-1 toggles)'),
    22030: ('MCC_SET_TOOLTIPS', 'bool bTooltips (-1 toggles)'),
    22031: ('MCC_AUDIO_ONLY_MODE', 'bool bAudioOnlyMode (-1 toggles)'),

    # Tools
    23000: ('MCC_IMPORT', 'int nFlags (1: bDisableAlreadyRunningWarning, 2: bFirstImportMode)'),
    23001: ('MCC_RIP_CD', 'ignore'),
    23002: ('MCC_BURN', 'ignore'),
    23003: ('MCC_RECORD_AUDIO', 'ignore'),
    23004: ('MCC_CONVERT', 'ignore'),
    23005: ('MCC_ANALYZE_AUDIO', 'ignore'),
    23006: ('MCC_MEDIA_EDITOR', 'ignore'),
    23007: ('MCC_CD_LABELER', 'ignore'),
    23008: ('MCC_OBSOLETE_23008', 'ignore'),
    23009: ('MCC_OBSOLETE_23009', 'ignore'),
    23010: ('MCC_SKIN_MANAGER', 'ignore'),
    23011: ('MCC_OPTIONS', 'int nPageID'),
    23012: ('MCC_RENAME_CD_FILES', 'ignore'),
    23013: ('MCC_OBSOLETE_23013', 'ignore'),
    23014: ('MCC_OBSOLETE_23014', 'ignore'),
    23015: ('MCC_HANDHELD_UPLOAD', 'loword: nDeviceSessionID (0 gets default), hiword: flags (1: sync only; 2: show warnings)'),
    23016: ('MCC_HANDHELD_UPDATE_UPLOAD_WORKER_FINISHED', 'int nDeviceSessionID'),
    23017: ('MCC_HANDHELD_CLOSE_DEVICE', 'int nDeviceSessionID'),
    23018: ('MCC_HANDHELD_SHOW_OPTIONS', 'int nDeviceSessionID'),
    23019: ('MCC_HANDHELD_INFO_DUMP', 'bool bShowInfo'),
    23020: ('MCC_IMPORT_AUTO_RUN_NOW', 'bool bSilent'),
    23021: ('MCC_IMPORT_AUTO_CONFIGURE', 'ignore'),
    23022: ('MCC_HANDHELD_EJECT', 'int nDeviceSessionID'),
    23023: ('MCC_RECORD_TV', 'ignore'),
    23024: ('MCC_FIND_AND_REPLACE', 'ignore'),
    23025: ('MCC_CLEAN_PROPERTIES', 'ignore'),
    23026: ('MCC_FILL_TRACK_ORDER', 'ignore'),
    23027: ('MCC_MOVE_COPY_FIELDS', 'ignore'),
    23028: ('MCC_REMOVE_TAGS', 'ignore'),
    23029: ('MCC_UPDATE_TAGS_FROM_DB', 'ignore'),
    23030: ('MCC_UPDATE_DB_FROM_TAGS', 'ignore'),
    23031: ('MCC_LOOKUP_TRACK_INFO_FROM_INTERNET', 'ignore'),
    23032: ('MCC_SUBMIT_TRACK_INFO_TO_INTERNET', 'ignore'),
    23033: ('MCC_OBSOLETE_23033', 'ignore'),
    23034: ('MCC_FILL_PROPERTIES_FROM_FILENAME', 'ignore'),
    23035: ('MCC_RENAME_FILES_FROM_PROPERTIES', 'ignore'),
    23036: ('MCC_COVER_ART_ADD_FROM_FILE', 'ignore'),
    23037: ('MCC_COVER_ART_QUICK_ADD_FROM_FILE', 'ignore'),
    23038: ('MCC_COVER_ART_GET_FROM_INTERNET', 'ignore'),
    23039: ('MCC_COVER_ART_SUBMIT_TO_INTERNET', 'ignore'),
    23040: ('MCC_COVER_ART_GET_FROM_SCANNER', 'ignore'),
    23041: ('MCC_COVER_ART_SELECT_SCANNER', 'ignore'),
    23042: ('MCC_COVER_ART_GET_FROM_CLIPBOARD', 'ignore'),
    23043: ('MCC_COVER_ART_COPY_TO_CLIPBOARD', 'ignore'),
    23044: ('MCC_COVER_ART_REMOVE', 'ignore'),
    23045: ('MCC_COVER_ART_PLAY', 'ignore'),
    23046: ('MCC_COVER_ART_SAVE_TO_EXTERNAL_FILE', 'ignore'),
    23047: ('MCC_COVER_ART_REBUILD_THUMBNAIL', 'ignore'),
    23048: ('MCC_RINGTONE', 'ignore'),
    23049: ('MCC_AUDIO_CALIBRATION', 'ignore'),
    23050: ('MCC_MARK_PLAYED', 'ignore'),
    23051: ('MCC_MARK_NOT_PLAYED', 'ignore'),
    23052: ('MCC_LINK_TRACKS', 'ignore'),
    23053: ('MCC_BREAK_TRACK_LINKS', 'ignore'),

    # Help
    24000: ('MCC_HELP_CONTENTS', 'ignore'),
    24001: ('MCC_HELP_HOWTO_IMPORT_FILES', 'ignore'),
    24002: ('MCC_HELP_HOWTO_PLAY_FILES', 'ignore'),
    24003: ('MCC_HELP_HOWTO_RIP', 'ignore'),
    24004: ('MCC_HELP_HOWTO_BURN', 'ignore'),
    24005: ('MCC_HELP_HOWTO_ORGANIZE_FILES', 'ignore'),
    24006: ('MCC_HELP_HOWTO_VIEW_SCHEMES', 'ignore'),
    24007: ('MCC_HELP_HOWTO_MANAGE_PLAYLISTS', 'ignore'),
    24008: ('MCC_HELP_HOWTO_EDIT_PROPERTIES', 'ignore'),
    24009: ('MCC_HELP_HOWTO_FIND', 'ignore'),
    24010: ('MCC_HELP_HOWTO_CONFIGURE', 'ignore'),
    24011: ('MCC_CHECK_FOR_UPDATES', 'ignore'),
    24012: ('MCC_BUY', 'ignore'),
    24013: ('MCC_INSTALL_LICENSE', 'ignore'),
    24014: ('MCC_REGISTRATION_INFO', 'ignore'),
    24015: ('MCC_PLUS_FEATURES', 'ignore'),
    24016: ('MCC_INTERACT', 'ignore'),
    24017: ('MCC_SYSTEM_INFO', 'ignore'),
    24018: ('MCC_ABOUT', 'ignore'),
    24019: ('MCC_CONFIGURE_DEBUG_LOGGING', 'ignore'),
    24020: ('MCC_WIKI', 'ignore'),
    24021: ('MCC_TEST', 'ignore'),
    24022: ('MCC_SHOW_EULA', 'ignore'),
    24023: ('MCC_BENCHMARK', 'ignore'),
    24023: ('MCC_UPGRADE_TO_MASTER_LICENSE', 'ignore'),

    # Tree
    25000: ('MCC_ADD_VIEW_SCHEME', 'ignore'),
    25001: ('MCC_EDIT_VIEW_SCHEME', 'ignore'),
    25002: ('MCC_OBSOLETE_25002', 'ignore'),
    25003: ('MCC_OBSOLETE_25003', 'ignore'),
    25004: ('MCC_OBSOLETE_25004', 'ignore'),
    25005: ('MCC_OBSOLETE_25005', 'ignore'),
    25006: ('MCC_OBSOLETE_25006', 'ignore'),
    25007: ('MCC_OBSOLETE_25007', 'ignore'),
    25008: ('MCC_TREE_ADD_DIRECTORY', 'ignore'),
    25009: ('MCC_TREE_IMPORT', 'ignore'),
    25010: ('MCC_TREE_ADD_CD_FOLDER', 'ignore'),
    25011: ('MCC_UPDATE_FROM_CD_DATABASE', 'ignore'),
    25012: ('MCC_SUBMIT_TO_CD_DATABASE', 'ignore'),
    25013: ('MCC_TREE_RIP', 'ignore'),
    25014: ('MCC_CLEAR_PLAYING_NOW', '0: all files; 1: leave playing file'),
    25015: ('MCC_COPY_LISTENING_TO', 'bool bPaste'),
    25016: ('MCC_TREE_SET_EXPANDED', '0: collapsed; 1: expanded'),
    25017: ('MCC_RESET_VIEW_SCHEMES', 'ignore'),
    25018: ('MCC_TREE_ERASE_CD_DVD', 'ignore'),
    25019: ('MCC_UPDATE_FROM_CDPLAYER_INI', 'ignore'),
    25020: ('MCC_TREE_EJECT', 'ignore'),
    25021: ('MCC_TREE_ADD_VIRTUAL_DEVICE', 'ignore'),
    25022: ('MCC_TREE_RENAME_PLAYLIST', 'int nPlaylistID'),
    25023: ('MCC_TWITTER_LISTENING_TO', 'ignore'),
    25024: ('MCC_SCROBBLE_LISTENING_TO', 'ignore'),

    # List
    26000: ('MCC_LIST_UPDATE_ORDER', 'ignore'),
    26001: ('MCC_LIST_SHUFFLE_ORDER', 'ignore'),
    26002: ('MCC_LIST_IMPORT', 'ignore'),
    26003: ('MCC_LIST_REMOVE_ORDER', 'ignore'),
    26004: ('MCC_LOCATE_FILE', 'int nLocation (-1: on disk (internal); -2: on disk (external); 0-n: library field index)'),
    26005: ('MCC_LIST_OBSOLETE_26005', 'ignore'),
    26006: ('MCC_LIST_INCREMENT_SELECTION', 'int nDelta'),
    26007: ('MCC_LIST_REMOVE_DUPLICATES', 'ignore'),
    26008: ('MCC_LIST_AUTO_SIZE_COLUMN', 'int nColumn, zero-based column index (-1: all)'),
    26009: ('MCC_LIST_CUSTOMIZE_VIEW', 'ignore'),
    26010: ('MCC_LIST_COPY_DISK_FILES', 'ignore'),
    26011: ('MCC_LIST_SET_RIP_CHECK', '0: uncheck, 1: check, -1: toggle'),
    26012: ('MCC_LIST_DOWNLOAD', 'ignore'),
    26013: ('MCC_LIST_GET_LIST_POINTER', 'ignore'),
    26014: ('MCC_LOCATE_STACK', 'ignore'),
    26015: ('MCC_SET_AS_STACK_TOP', 'ignore'),
    26016: ('MCC_EXPAND_STACK', 'ignore'),
    26017: ('MCC_COLLAPSE_STACK', 'ignore'),
    26018: ('MCC_AUTOSTACK', '0: by name, 1: artist, album, name, 2: Artist, Album, Track # and Name'),
    26019: ('MCC_CHECK_STACKS', 'ignore'),
    26020: ('MCC_STACK', 'int nZeroBasedSelection'),
    26021: ('MCC_UNSTACK', 'ignore'),
    26022: ('MCC_ADD_TO_STACK', 'ignore'),
    26023: ('MCC_PANE_RESET_SELECTION', 'int nPaneIndex (-1 resets all)'),
    26024: ('MCC_LIST_REMOVE_ALL', 'ignore'),
    26025: ('MCC_LIST_LOCK', 'bool bLock (-1 toggles)'),
    26026: ('MCC_PANE_SET_EXPANDED', 'loword: nPaneIndex, hiword: 0: collapsed; 1: expanded'),

    # System
    27000: ('MCC_KEYSTROKE', 'int nKeyCode'),
    27001: ('MCC_SHUTDOWN', 'int nMode (0: shutdown; 1: sleep; 2: hibernate; 3: restart) (based on CSystemShutdown::EShutdownModes)'),

    # Playback Engine
    28000: ('MCC_PLAYBACK_ENGINE_ZOOM_IN', 'ignore'),
    28001: ('MCC_PLAYBACK_ENGINE_ZOOM_OUT', 'ignore'),
    28002: ('MCC_PLAYBACK_ENGINE_UP', 'ignore'),
    28003: ('MCC_PLAYBACK_ENGINE_DOWN', 'ignore'),
    28004: ('MCC_PLAYBACK_ENGINE_LEFT', 'ignore'),
    28005: ('MCC_PLAYBACK_ENGINE_RIGHT', 'ignore'),
    28006: ('MCC_PLAYBACK_ENGINE_ENTER', 'ignore'),
    28007: ('MCC_PLAYBACK_ENGINE_FIRST', 'ignore'),
    28008: ('MCC_PLAYBACK_ENGINE_LAST', 'ignore'),
    28009: ('MCC_PLAYBACK_ENGINE_NEXT', 'ignore'),
    28010: ('MCC_PLAYBACK_ENGINE_PREVIOUS', 'ignore'),
    28011: ('MCC_PLAYBACK_ENGINE_PAUSE', 'bool bPause (-1 toggles)'),
    28012: ('MCC_IMAGE_PAN_AND_ZOOM', 'bool bPanAndZoom (-1 toggles)'),
    28013: ('MCC_IMAGE_TOGGLE_EFFECT', 'int nDelta'),
    28014: ('MCC_IMAGE_RAPID_ZOOM', 'int nRapidZoom'),
    28015: ('MCC_DVD_SET_AUDIO_STREAM', 'int nAudioStream (-1 toggles)'),
    28016: ('MCC_DVD_SHOW_MENU', 'ignore'),
    28017: ('MCC_TV_RECORD', 'ignore'),
    28018: ('MCC_TV_SNAPSHOT', 'ignore'),
    28019: ('MCC_TV_CHANGE_STANDARD', 'ignore'),
    28020: ('MCC_PLAYBACK_ENGINE_OSD_VIDEO_PROC_AMP', 'int nIndex (0 for brightness, 1 for contrast, etc. -1 cycles)'),
    28021: ('MCC_PLAYBACK_ENGINE_SET_CUR_VIDEO_PROC_AMP', 'int nStep (... -2, -1, 1, 2, etc. 0 is invalid and will default to 1)'),
    28022: ('MCC_PLAYBACK_ENGINE_SET_ASPECT_RATIO', '-1: cycles; 0 - 8: selects individual Aspect Ratio Modes'),
    28023: ('MCC_PLAYBACK_ENGINE_SCROLL_UP', 'ignore'),
    28024: ('MCC_PLAYBACK_ENGINE_SCROLL_DOWN', 'ignore'),
    28025: ('MCC_PLAYBACK_ENGINE_SCROLL_LEFT', 'ignore'),
    28026: ('MCC_PLAYBACK_ENGINE_SCROLL_RIGHT', 'ignore'),
    28027: ('MCC_TV_SET_SAVE_TIME_SHIFTING', 'int nSaveMode (0 - 6, -1 cycles by incrementing, -2 cycles by decrementing)'),
    28028: ('MCC_PLAYBACK_ENGINE_ZOOM_TO_PRESET', 'int 0 to fit window, 1 for 100%, 2 for 200%'),
    28029: ('MCC_TV_SCAN_PROGRAMMING_EVENTS', 'ignored'),
    28030: ('MCC_TV_CHANGE_CHANNEL_KEY', 'int nKey'),
    28031: ('MCC_TV_PLAY_CHANNEL_POSITION', 'int Playlist position'),
    28032: ('MCC_PLAYBACK_ENGINE_SET_SUBTITLES', 'int nIndex (-1 toggles forward, -2 toggles backwards)'),
    28033: ('MCC_PLAYBACK_ENGINE_SET_AUDIO_STREAM', 'int nIndex (-1 toggles forward, -2 toggles backwards)'),
    28034: ('MCC_PLAYBACK_ENGINE_SET_VIDEO_STREAM', 'int nIndex (-1 toggles forward, -2 toggles backwards)'),
    28035: ('MCC_PLAYBACK_ENGINE_VIDEO_SCREEN_GRAB', '0: use as thumbnail; 1: save as external file'),
    28036: ('MCC_PLAYBACK_ENGINE_VIDEO_LIPSYNC', 'int nShiftMS'),
    28037: ('MCC_PLAYBACK_ENGINE_SET_SUBTITLE_TIMING', 'int nChangeMS'),
    28038: ('MCC_PLAYBACK_ENGINE_VIDEO_ZOOM', 'int nZoomAmount (100 is 1.0)'),

    # Other
    30000: ('MCC_RELOAD_MC_VIEW', 'ignore'),
    30001: ('MCC_CUSTOMIZE_TOOLBAR', 'ignore'),
    30002: ('MCC_PLAY_TV', 'int nChannelNumber, user assigned channel number'),
    30003: ('MCC_UPDATE_WEBPAGES', 'ignore'),
    30004: ('MCC_SHOW_RUNNING_MC', 'bool bToggleVisibility'),
    30005: ('MCC_SHOW_MENU', 'int nMenuID'),
    30006: ('MCC_TUNE_TV', 'ignore'),
    30007: ('MCC_PLAY_PLAYLIST', 'int nPlaylistID'),
    30008: ('MCC_SENDTO_TOOL', '0: labeler; 1: media editor; 2: default editor; 3: ftp upload; 4: email; 5 Menalto Gallery; 6 Web Gallery'),
    30009: ('MCC_SHOW_VIEW_INFO', 'new CMCViewInfo * (for internal use only)'),
    30010: ('MCC_OBSOLETE_30010', 'ignore'),
    30011: ('MCC_DEVICE_CHANGED', 'new DEVICE_CHANGE_INFO * (for internal use only)'),
    30012: ('MCC_CONFIGURE_THEATER_VIEW', 'ignore'),
    30013: ('MCC_SET_STATUSTEXT', 'BSTR bstrText (deleted by receiver)'),
    30014: ('MCC_UPDATE_UI_AFTER_ACTIVE_WINDOW_CHANGE', 'ignore'),
    30015: ('MCC_REENUM_PORTABLE_DEVICES', 'bool bDeviceConnected'),
    30016: ('MCC_PLAY_ADVANCED', 'PLAY_COMMAND * pCommand (deleted by receiver)'),
    30017: ('MCC_UPDATE_STATUS_BAR', 'ignore'),
    30018: ('MCC_REQUEST_PODCAST_UPDATE', 'ignore'),
    30019: ('MCC_REQUEST_PODCAST_PURGE', 'ignore'),
    30020: ('MCC_OBSOLETE_30020', 'ignore'),
    30021: ('MCC_SHOW_INVALID_CD_VOLUME_WARNING', 'TCHAR cDriveLetter'),
    30022: ('MCC_PLAY_TV_CHANNEL_FOR_CLIENT', 'the MFKEY key of the TV channel to be played'),
    30023: ('MCC_STOP_SERVING_TV_FILE', 'CTVPlayer *: pointer to TVPlayer object serving the file'),
    30025: ('MCC_SET_OSD_ENABLED', '-1 toggles, 1 turns on, 0 turns off (/mcc 30025,-1)'),

    # Image Tools
    31000: ('MCC_IMAGE_SET_DESKTOP_BACK', 'ignore'),
    31001: ('MCC_IMAGE_ROTATE_LEFT', 'ignore'),
    31002: ('MCC_IMAGE_ROTATE_RIGHT', 'ignore'),
    31003: ('MCC_IMAGE_ROTATE_UPSIDEDOWN', 'ignore'),
    31004: ('MCC_IMAGE_RESIZE', 'ignore'),
    31005: ('MCC_IMAGE_EDIT', 'int nFileKey'),
    31006: ('MCC_IMAGE_DELETE', 'int nFileKey'),
    31007: ('MCC_IMAGE_PREVIEW_SHOW', 'ignore'),
    31008: ('MCC_IMAGE_PREVIEW_HIDE', 'ignore'),
    31009: ('MCC_IMAGE_LOCATE_ON_MAP', 'ignore'),

    # Query
    32000: ('MCC_QUERY_UI_MODE', 'bool bInternalMode; Exit status is current UI_MODES'),

    # Commands
    33000: ('MCC_GET_SELECTED_FILES', 'loword: GET_SELECTION_MODES Mode, hiword: short nFlags (1: for playback)'),
    33001: ('MCC_PRINTVIEW', 'ignore'),
    33002: ('MCC_OUTPUT', 'int nPlaylistID (-1 for active view)'),
    33003: ('MCC_SETFOCUS', 'ignore'),
    33004: ('MCC_SELECT_FILES', 'CMediaArray *'),
    33005: ('MCC_DOUBLE_CLICK', 'ignore'),
    33006: ('MCC_PLAY_OR_SHOW', 'ignore'),
    33007: ('MCC_SHOW_CURRENT_FILE', 'int nFlags (1: force, 2: select)'),
    33008: ('MCC_BUY_SELECTED_TRACKS', 'int nPurchaseFlags'),
    33009: ('MCC_BUY_ALL_TRACKS', 'int nPurchaseFlags'),
    33010: ('MCC_BUY_ALBUM', 'int nPurchaseFlags'),
    33011: ('MCC_UPDATE_AFTER_PLUGIN_INSTALLED', 'ignore'),
    33012: ('MCC_UPDATE_AFTER_SKIN_INSTALLED', 'bool bMiniView'),

    # Notifications
    34000: ('MCC_NOTIFY_FONT_CHANGED', 'ignore'),
    34001: ('MCC_NOTIFY_VIEW_CHANGED', 'ignore'),
    34002: ('MCC_NOTIFY_BEFORE_ACTIVE_VIEW_CHANGED', 'ignore'),
    34003: ('MCC_NOTIFY_ACTIVE_VIEW_CHANGED', 'ignore'),
    34004: ('MCC_NOTIFY_PLAYER_INFO_CHANGED', 'PLAYER_INFO_CHANGES nChange'),
    34005: ('MCC_NOTIFY_TOOLTIPS_CHANGED', 'bool bEnabled'),
    34006: ('MCC_NOTIFY_OPTIONS_CHANGED', 'ignore'),
    34007: ('MCC_UPDATE', 'int nFlags'),
    34008: ('MCC_NOTIFY_FOCUS_CHANGED', 'ignore'),
    34009: ('MCC_SAVE_PROPERTIES', 'ignore'),
    34010: ('MCC_NOTIFY_UI_MODE_CHANGED', 'UI_MODES NewMode'),
    34011: ('MCC_NOTIFY_SELECTION_CHANGED', 'int nViewKey'),
    34012: ('MCC_NOTIFY_FILE_CHANGED', 'int nFileKey (-1: invalidates all files)'),
    34013: ('MCC_NOTIFY_FILE_STATUS_CHANGED', 'int nFileKey (-1: invalidates all files)'),
    34014: ('MCC_NOTIFY_FILE_ENSURE_VISIBLE', 'int nFileKey'),
    34015: ('MCC_NOTIFY_GET_TAB_HWNDS', 'ignore'),
    34016: ('MCC_NOTIFY_BURNER_QUEUE_CHANGED', 'int nFlags (1: folder change)'),
    34017: ('MCC_NOTIFY_BURNER_PROGRESS_CHANGED', 'int nPercentage'),
    34018: ('MCC_NOTIFY_BURNER_STATUS_CHANGED', 'ignore'),
    34019: ('MCC_NOTIFY_BURNER_STARTED', 'ignore'),
    34020: ('MCC_NOTIFY_BURNER_FINISHED_INTERNAL', 'ignore'),
    34021: ('MCC_NOTIFY_BURNER_FINISHED', 'ignore'),
    34022: ('MCC_NOTIFY_BURNER_FAILED_INTERNAL', 'ignore'),
    34023: ('MCC_NOTIFY_BURNER_FAILED', 'ignore'),
    34024: ('MCC_NOTIFY_BURNER_CLOSE_UI', 'ignore'),
    34025: ('MCC_NOTIFY_BURNER_PREPARE_FOR_NEXT_COPY', 'LPCTSTR pStatus'),
    34026: ('MCC_NOTIFY_RIP_STARTED', 'ignore'),
    34027: ('MCC_NOTIFY_RIP_FINISHED', 'ignore'),
    34028: ('MCC_NOTIFY_RIP_FAILED', 'LPCTSTR pError'),
    34029: ('MCC_NOTIFY_RIP_PROGRESS_CHANGED', 'ignore'),
    34030: ('MCC_NOTIFY_RIP_QUEUE_CHANGED', 'ignore'),
    34031: ('MCC_NOTIFY_DVD_RIP_STARTED', 'ignore'),
    34032: ('MCC_NOTIFY_DVD_RIP_FINISHED', 'ignore'),
    34033: ('MCC_NOTIFY_DVD_RIP_FAILED', 'int nErrorCode'),
    34034: ('MCC_NOTIFY_DVD_RIP_PROGRESS_CHANGED', 'int nPercent'),
    34035: ('MCC_NOTIFY_DOWNLOAD_FINISHED', 'int nFileKey (-1: unknown)'),
    34036: ('MCC_NOTIFY_DOWNLOAD_FAILED', 'int nFileKey (-1: unknown)'),
    34037: ('MCC_NOTIFY_DOWNLOAD_STATUS_CHANGED', 'ignore'),
    34038: ('MCC_NOTIFY_STATUS_CHECKER_COMPLETE', 'ignore'),
    34039: ('MCC_NOTIFY_CURRENT_ZONE_CHANGED', 'ignore'),
    34040: ('MCC_NOTIFY_DISPLAY_OWNER_CHANGED', 'JRWnd * pwndOwner'),
    34041: ('MCC_NOTIFY_AFTER_FIRST_UPDATE_LAYOUT_WINDOW', 'ignore'),
    34042: ('MCC_NOTIFY_AFTER_FIRST_UPDATE_APPLY_VIEW_STATE', 'ignore'),
    34043: ('MCC_NOTIFY_PROCESS_TIME_REMAINING', 'int nSecondsRemaining'),
    34044: ('MCC_NOTIFY_UI_UPDATE_ENABLE_DISABLE_STATES', 'ignore'),
    34045: ('MCC_NOTIFY_UI_SKIN_CHANGED', 'ignore'),
    34046: ('MCC_UPDATE_WINDOW_LAYOUT', 'ignore'),
    34047: ('MCC_NOTIFY_SAVE_UI_BEFORE_SHUTDOWN', 'ignore'),
    34048: ('MCC_OBSOLETE_34046', 'ignore'),
    34049: ('MCC_NOTIFY_PLAYLIST_FILES_CHANGED', 'int nPlaylistID'),
    34050: ('MCC_NOTIFY_PLAYLIST_INFO_CHANGED', 'int nPlaylistID'),
    34051: ('MCC_NOTIFY_PLAYLIST_ADDED_INTERNAL', 'int nPlaylistID'),
    34052: ('MCC_NOTIFY_PLAYLIST_ADDED_BY_USER', 'int nPlaylistID'),
    34053: ('MCC_NOTIFY_PLAYLIST_REMOVED', 'int nPlaylistID'),
    34054: ('MCC_NOTIFY_PLAYLIST_COLLECTION_CHANGED', 'ignore'),
    34055: ('MCC_NOTIFY_PLAYLIST_PROPERTIES_CHANGED', 'int nPlaylistID'),
    34056: ('MCC_NOTIFY_HANDHELD_UPLOAD_STARTED', 'int nDeviceSessionID (0 gets default)'),
    34057: ('MCC_NOTIFY_HANDHELD_AFTER_DEVICE_CHANGED', 'ignore'),
    34058: ('MCC_NOTIFY_HANDHELD_QUEUE_CHANGED', 'ignore'),
    34059: ('MCC_NOTIFY_HANDHELD_INFO_COMPLETE', 'ignore'),
    34060: ('MCC_NOTIFY_HANDHELD_AFTER_UPLOAD_FINISHED', 'ignore'),
    34061: ('MCC_NOTIFY_COMPACT_MEMORY', 'ignore'),
    34062: ('MCC_NOTIFY_SEARCH_CHANGED', 'ignore'),
    34063: ('MCC_NOTIFY_SEARCH_CONTEXT_CHANGED', 'ignore'),
    34064: ('MCC_NOTIFY_UPDATE_SHOPPING_CART', 'JRStoreBase * pStore'),
    34065: ('MCC_NOTIFY_UPDATE_NAVIGATION_TRAIL', 'ignore'),
    34066: ('MCC_NOTIFY_IMPORT_STARTED', 'bool bSilent'),
    34067: ('MCC_NOTIFY_IMPORT_FINISHED', 'bool bSilent'),
    34068: ('MCC_NOTIFY_ROTATED_IMAGES', 'MFKEY nKey'),
    34069: ('MCC_NOTIFY_LOGIN_STATE_CHANGE', 'bool bLoggedIn'),
    34070: ('MCC_NOTIFY_MYGAL_PROGRESS', 'ignore'),
    34071: ('MCC_NOTIFY_MYGAL_DONE', 'ignore'),
    34072: ('MCC_NOTIFY_PODCAST_CHANGED', 'ignore'),
    34073: ('MCC_NOTIFY_PODCAST_SETTINGS_CHANGED', 'ignore'),
    34074: ('MCC_NOTIFY_CONVERT_PROGRESS', 'ignore'),
    34075: ('MCC_NOTIFY_CONVERT_UPDATE', 'ignore'),
    34076: ('MCC_NOTIFY_BREADCRUMBS_CHANGED', 'ignore'),
    34077: ('MCC_NOTIFY_UI_LANGUAGE_CHANGED', 'ignore'),
    34078: ('MCC_NOTIFY_INSTALLED_PLUGINS_CHANGED', 'ignore'),
    34079: ('MCC_NOTIFY_SUGGESTED_MUSIC_CHANGED', 'ignore'),
    34080: ('MCC_NOTIFY_VIEW_SETTINGS_CHANGED', 'int nFlags'),
    34081: ('MCC_NOTIFY_BEFORE_CONFIGURE_VIEW_SETTINGS', 'ignore'),
    34082: ('MCC_NOTIFY_TV_RECORDING_CHANGED', 'ignore'),
    34083: ('MCC_NOTIFY_TV_PROGRAMMING_GUIDE_CHANGED', 'ignore'),
    34084: ('MCC_NOTIFY_TV_CHANNELS_CHANGED', 'ignore'),
    34085: ('MCC_NOTIFY_TV_RECORDING_STARTED', 'ignore'),
    34086: ('MCC_NOTIFY_TV_RECORDING_FINISHED', 'ignore'),
    34087: ('MCC_NOTIFY_IMPORT_FILES_ADDED', 'ignore'),
    34088: ('MCC_NOTIFY_PLAYBACK_OPTIONS_CHANGED', 'ignore'),
    34089: ('MCC_NOTIFY_BEFORE_LAYOUT_USER_INTERFACE', 'ignore'),
    34090: ('MCC_NOTIFY_AFTER_LAYOUT_USER_INTERFACE', 'ignore'),
    34091: ('MCC_NOTIFY_ZONE_ADDED_OR_REMOVED', 'int nZoneID (PLAYER_ZONE_ID_UNDEFINED means multiple changes)'),
    34092: ('MCC_NOTIFY_ZONE_LINKED_OR_UNLINKED', 'ignore'),
    34093: ('MCC_NOTIFY_LIBRARY_LOCATIONS_CHANGED', 'ignore'),
    34094: ('MCC_NOTIFY_DSP_SETTINGS_CHANGED_IN_CODE', 'int nZoneID'),
    34095: ('MCC_NOTIFY_OPTICAL_DISC_CHANGED', 'ignore'),

    # Store
    35000: ('MCC_STORE_DOWNLOAD', 'bool bAllowPurchaseType'),
    35001: ('MCC_STORE_PURCHASE', 'MFKEY nKey'),
    35002: ('MCC_STORE_SEARCH_AMAZON', 'MFKEY nKey'),
    35003: ('MCC_STORE_SEARCH_AMAZON_MP3_STORE', 'MFKEY nKey'),
    35004: ('MCC_STORE_TSHIRT', 'MFKEY nKey')
}

# Build two dictionaries for retrieval by code (numeral) or command (name)
mcc_cmds = dict(_cmds)

mcc_codes = dict()

for (code, (cmd, param)) in _cmds.items():
    mcc_codes[cmd] = code

